pipeline {
    agent {
        label "master"
    }
    stages {
        stage("Check Running Jobs") {
            steps {
                script {

                    def nodeName = "master"
                    def instanceId = "instance-id"
                    while (true) {
                        def nodeName = "master"
                        def computer = jenkins.model.Jenkins.instance.getComputer(nodeName)
                        if (computer) {
                            def busyExecutors = computer.countBusy()
                            echo "Busy Executors: ${busyExecutors}"
                        } else {
                            echo "Knoten ${nodeName} nicht gefunden!"
                        }
                        sleep(5)
                    }
                }
            }
        }
    }
}
//println "Hello PSI from groovy!"