pipeline {
    agent nodeName
    stages {
        stage("start build") {
            agent {
                label "build-node"
            }

            steps {
                script {
                    while (true) {
                        println "Building..."
                        sleep(5)
                    }
                }
            }
        }
    }
}