pipeline {
    agent nodeName
    stages {
        stage("Check and start node") {
            agent {
                label "main"
            }

            steps {
                script {
                    def nodeName = "build-node"
                    def instanceId = "instance-id"

                    def isOnline = jenkins.model.Jenkins.instance.computers.find { it.name == nodeName }?.offline == false

                    if (!isOnline) {
                        echo "Node ${nodeName} ist offline. Starte Instanz..."
                        //Start here
                    }
                    else {
                        echo "Node ${nodeName} ist bereits online."
                    }
                }
            }
        }
    }
}