pipeline {
    agent {
        label "master"
    }
    stages {
        stage("start build") {
            steps {
                script {
                    while (true) {
                        println "Building..."
                        sleep(5)
                    }
                }
            }
        }
    }
}